version: "3.8"

services:
  stockfish:
    build:
      context: ./stockfish  # Path to the Dockerfile directory
      dockerfile: Dockerfile  # Optional if the file is named 'Dockerfile'
    volumes:
      - ./stockfish:/app  # Sync changes for development
    ports:
      - "5123:5123"  # Expose API if needed
    restart: unless-stopped  # Restart policy
